

clean:
	-rm -f *.prt
	-rm -f *.mod
	-rm -f *.grn
	-rm -f *.shd
	-rm -f *.rts
	-rm -f *.ray
	-rm -f *.brc
	-rm -f *.irc
	-rm -f *.dat
	-rm -f *.asc
	-rm -f fort.*
	-rm -f *.moA
	-rm -f *.mat
	(cd KoreanSeas; 	make clean)
	(cd Parabot; 		make clean)
	(cd Taiwan; 		make clean)
	(cd Seamount; 		make clean)
	(cd PerfectWedge; 	make clean)
	(cd TruncatedWedge; 	make clean)
	(cd DoubleSeamount; 	make clean)
	(cd Munk;	 	make clean)
